// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9hJSkfZC9b4RF603IldCnH_ehI98w3dM',
    appId: '1:399410367882:web:06feab0aefa89712514c73',
    messagingSenderId: '399410367882',
    projectId: 'flutter-login-app-e6be4',
    authDomain: 'flutter-login-app-e6be4.firebaseapp.com',
    storageBucket: 'flutter-login-app-e6be4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJDKm-AP1LpGwkvGAQcGYkYyCDXYA2FU',
    appId: '1:399410367882:android:cdc94145ac7450c6514c73',
    messagingSenderId: '399410367882',
    projectId: 'flutter-login-app-e6be4',
    storageBucket: 'flutter-login-app-e6be4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1RHQe6jV8iBYcYUweQXii9SZYfp_RwzY',
    appId: '1:399410367882:ios:6c27112fd8882808514c73',
    messagingSenderId: '399410367882',
    projectId: 'flutter-login-app-e6be4',
    storageBucket: 'flutter-login-app-e6be4.appspot.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1RHQe6jV8iBYcYUweQXii9SZYfp_RwzY',
    appId: '1:399410367882:ios:c229ebe745a6ef8f514c73',
    messagingSenderId: '399410367882',
    projectId: 'flutter-login-app-e6be4',
    storageBucket: 'flutter-login-app-e6be4.appspot.com',
    iosBundleId: 'com.example.loginpage.RunnerTests',
  );
}
